apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-doctor
  labels:
    app: hello-doctor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-doctor
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 4
  template:
    metadata:
      labels:
        app: hello-doctor
    spec:
      containers:
      - name: php
        image: hello-doctor-php:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
      - name: nginx
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-doctor-service
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: hello-doctor
        
